### ISSUE TITLE
Items that are not the Primal Blood essence are getting deleted.

### ISSUE THREAD

**Issue by Odjit** [CrimsonMods/CrimsonMoon#2]
If you drop other items in the area, or more primals than necessary, it eats all, regardless. You need to add a filter for the prefab to your use of KC's DropItemsService, and probably also check for an amount to remove from the container.

**Comment by SkyTech6** [comment]
That's actually intentional implementation. It is designed to not be a clear trigger, but something for players to test and learn what is the minimum they can provide. Kind of like a secret MMO trigger.

Changing it from my original design isn't something I will be doing for CrimsonMods, however I'm more than happy to accept a Pull Request for this functionality long as it includes an optional config flag.
